### ISSUE TITLE
tensorflow.train.threading not working in 0.12

### ISSUE THREAD

**Issue by gitmenonsandu** [Russell91/TensorBox#140]
Traceback (most recent call last):
  File "train.py", line 537, in <module>
    main()
  File "train.py", line 534, in main
    train(H, test_images=[])
  File "train.py", line 457, in train
    t = tf.train.threading.Thread(target=thread_loop,
AttributeError: 'module' object has no attribute 'threading'

**Comment by parhartanvir** [comment]
You might have installed tensorflow from source. I had a similar issue. I just used the python threading module.
`import threading` and do `t=threading.Thread(same stuff)`

**Comment by gitmenonsandu** [comment]
The code goes like this  :
t = tf.train.threading.Thread(target=thread_loop,args=(sess, enqueue_op, phase, gen))
t.daemon = True
t.start()

What do I replace?
t=threadin.Thread(  ?   )

**Comment by parhartanvir** [comment]
I apologize, I wasn't clear enough.

In python 3.4,
`import threading` 

Then replace
`t = tf.train.threading.Thread(target=thread_loop,args=(sess, enqueue_op, phase, gen))`
with 
`t = threading.Thread(target=thread_loop,args=(sess, enqueue_op, phase, gen))`
