### PR TITLE
Change `tf.train.threading.Thread` to `threading.Thread`

### LINKED ISSUE #140: tensorflow.train.threading not working in 0.12
Traceback (most recent call last):
  File "train.py", line 537, in <module>
    main()
  File "train.py", line 534, in main
    train(H, test_images=[])
  File "train.py", line 457, in train
    t = tf.train.threading.Thread(target=thread_loop,
AttributeError: 'module' object has no attribute 'threading'

### PR DESCRIPTION
**Pull request by mrry**
The former was an undocumented and accidental inclusion in the `tf.train` module, and it is no longer exported. Since it was just an alias for the Python standard `threading` module, use that instead.

Fixes #140.

### CODE REVIEW

**Comment by Russell91** [comment]
Oh wow, so that is what was going on! It was like they removed it from tf.train and didn't put it anywhere else.
